---

 - name: Os release
   shell: cat /etc/redhat-release
   register: os_old_release
   when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
   tags:
     - updateCentosOS

 - name: Kernel Version
   shell: uname -r
   register: kernel_old_version
   when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
   tags:
     - updateCentosOS

 - debug:
     msg: "OS Release: {{ os_old_release.stdout }} | Kernel Version: {{ kernel_old_version.stdout }}"
   when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
   tags:
     - updateCentosOS

 - name: Update OS
   yum:
     name: "*"
     state: latest
     update_cache: yes
   when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
   tags:
     - updateCentosOS

 - name: System Reboot
   reboot:
   when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
   tags:
     - updateCentosOS

 - name: Removing Old Kernels
   command: package-cleanup --oldkernels --count=1 -y
   when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
   tags:
     - updateCentosOS

 - name: Os release
   shell: cat /etc/redhat-release
   register: os_new_release
   when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
   tags:
     - updateCentosOS

 - name: Kernel Version
   shell: uname -r
   register: kernel_new_version
   when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
   tags:
     - updateCentosOS

 - debug:
     msg: "OS Release: {{ os_new_release.stdout }} | Kernel Version: {{ kernel_new_version.stdout }}"
   when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
   tags:
     - updateCentosOS

...
